:_newdoc-version: 2.18.5
:_template-generated: 2025-09-11
:_mod-docs-content-type: PROCEDURE

[id="virt-inserting-a-cd-rom-in-a-vm-by-using-the-web-console_{context}"]
= virt-Inserting a CD-ROM in a VM by using the web console

TBA intro

[IMPORTANT]
====
This feature is currently provided as a Technology Preview in {product-title}. For more information, see link:https://access.redhat.com/support/offerings/techpreview/?extIdCarryOver=true&sc_cid=RHCTG0180000371695[Technology Preview features - Scope of Support] in Red Hat Knowledgebase.
====

.Prerequisites
* The `DeclarativeHotplugVolumes` feature gate must be enabled. To ensure this, the `HyperConverged` CR must contain the ``DeclarativeHotplugVolumes` line in the `spec.configuration.developerConfiguration.featureGates` configuration section:

+
[source,yaml]
----
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - DeclarativeHotplugVolumes
----
+
[Warning]
====
The `DeclarativeHotplugVolumes` is incompatible with the `HotplugVolumes` feature gate, which is required for using ephemeral volumes. To use `DeclarativeHotplugVolumes`, you must also remove `HotplugVolumes` from the `HyperConverged` CR.
====

.Procedure

. In the {product-title} web console, go to `Virtualization` → `VirtualMachines`.

. Click the name of the VM in which you want to insert the CD-ROM.

. On the VM details page, click the `Configuration` tab.

. Open the `Storage` pane.

. Click `Add`.
+
A drop-down menu opens.

. Click `CD-ROM`.

. In the `Name` field, add a name for the CD-ROM drive device.

. Optional: To upload a new ISO file, ensure that the `` line is checked.

. Click `Add`.

. TODO: the rest of the steps

// .Verification

// .Troubleshooting


// .Next steps


// [role="_additional-resources"]
// .Additional resources
// * TBA?

