:_newdoc-version: 2.18.5
:_template-generated: 2025-09-11
:_mod-docs-content-type: PROCEDURE

[id="virt-inserting-a-cd-rom-in-a-vm-by-using-the-web-console_{context}"]
= virt-Inserting a CD-ROM in a VM by using the web console

TBA intro

[IMPORTANT]
====
This feature is currently provided as a Technology Preview in {product-title}. For more information, see link:https://access.redhat.com/support/offerings/techpreview/?extIdCarryOver=true&sc_cid=RHCTG0180000371695[Technology Preview features - Scope of Support] in Red Hat Knowledgebase.
====

.Prerequisites
* A bulleted list of conditions that must be satisfied before the user starts the steps in this module.
* Prerequisites can be full sentences or sentence fragments; however, prerequisite list items must be parallel.
* Do not use imperative statements in the Prerequisites section.

.Procedure

. In the {product-title} web console, go to `Virtualization` → `VirtualMachines`.

. Click the name of the VM in which you want to insert the CD-ROM.

. On the VM details page, click the `Configuration` tab.

. TODO: the rest of the steps

// .Verification

// .Troubleshooting


// .Next steps


// [role="_additional-resources"]
// .Additional resources
// * TBA?

