:_newdoc-version: 2.18.5
:_template-generated: 2025-09-11
:_mod-docs-content-type: PROCEDURE

[id="virt-inserting-a-cd-rom-in-a-vm-by-using-the-command-line_{context}"]
= Inserting a CD-ROM in a VM by using the command line

// See https://kubevirt.io/user-guide/storage/hotplug_volumes/#inject-cd-rom for upstream info

TBA intro

[IMPORTANT]
====
This feature is currently provided as a Technology Preview in {product-title}. For more information, see link:https://access.redhat.com/support/offerings/techpreview/?extIdCarryOver=true&sc_cid=RHCTG0180000371695[Technology Preview features - Scope of Support] in Red Hat Knowledgebase.
====

.Prerequisites

* You have an ISO image of a CD-ROM available in the cluster 

.Procedure

. Open the configuration of the VM in which you want to insert the CD-ROM:
+
[source,terminal]
----
$ oc edit _<vm-name>_ _<namespace>_
----
+
where:

* _<vm-name>_ is the name of the VM
* _<project>_ is the name of the project name space that contains the VM

. Add a `cdrom` disk to the `spec.template.spec.domains.devices.disks` section of the configuration:
+
[source,yaml]
----
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        devices:
          disks:
          - cdrom:
              bus: sata
              name: cdrom
# ...
----

. If the VM is running, shut it down.

. Insert a CD-ROM volume in the `spec.template.spec.volumes` section of the configuration, for example as follows:
+
[source,yaml]
----
      volumes:
      - dataVolume:
          name: cdrom-example
          hotpluggable: true
        name: cdrom
----
+
[NOTE]
====
You can also do this when the VM is running.
====

. Optional: Eject the CD-ROM volume. To do so, remove the `cdrom` device from the `spec.template.spec.volumes` section of the VM configuration.

// [role="_additional-resources"]
// .Additional resources
// * TBA?

